import me.zolotov.kodepoint.generator.UnicodeVersion
import me.zolotov.kodepoint.generator.generateUcdDiff
import me.zolotov.kodepoint.generator.generateUnicodeData
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    id("kodepoint.multiplatform")
}

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/sources/unicode-data"))
            dependencies {
                implementation(project(":common"))
            }
        }
        jvmTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

val generateUnicodeData = tasks.register("generateUnicodeData") {
    val unicodeVersion = providers.gradleProperty("kodepoint.unicodeVersion")
    val outputDir = layout.buildDirectory.dir("generated/sources/unicode-data")
    val cacheDir = layout.buildDirectory.dir("unicode-cache")
    val characterDataMetricsReport = layout.buildDirectory.file("reports/character-data/metrics.json")
    inputs.property("unicodeVersion", unicodeVersion)
    outputs.dir(outputDir)
    outputs.file(characterDataMetricsReport)

    doLast {
        generateUnicodeData(
            UnicodeVersion(unicodeVersion.get()),
            outputDir.get().asFile.toPath(),
            cacheDir.get().asFile.toPath(),
            "Generated by ./gradlew :unicode:generateUnicodeData",
            characterDataMetricsReport.get().asFile.toPath()
        )
    }
}

val generateUcdDiff = tasks.register("generateUcdDiff") {
    description = "Write the UCD delta between the toolchain JDK's Unicode version and the tables' version for ValidationTest."
    val tablesVersion = providers.gradleProperty("kodepoint.unicodeVersion")
    val jvmVersion = providers.gradleProperty("kodepoint.jvmUnicodeVersion")
    val cacheDir = layout.buildDirectory.dir("unicode-cache")
    val outputDir = layout.buildDirectory.dir("generated/resources/ucd-diff")
    inputs.property("tablesVersion", tablesVersion)
    inputs.property("jvmVersion", jvmVersion)
    outputs.dir(outputDir)

    doLast {
        generateUcdDiff(
            from = UnicodeVersion(jvmVersion.get()),
            to = UnicodeVersion(tablesVersion.get()),
            cacheDir = cacheDir.get().asFile.toPath(),
            output = outputDir.get().asFile.toPath().resolve("ucd-diff.txt")
        )
    }
}

kotlin.sourceSets.named("jvmTest") {
    resources.srcDir(generateUcdDiff)
}

tasks.register("characterDataMetrics") {
    group = "reporting"
    description = "Generate CharacterData size metrics as JSON."
    dependsOn(generateUnicodeData)
    doLast {
        println("CharacterData metrics report: ${layout.buildDirectory.file("reports/character-data/metrics.json").get().asFile}")
    }
}

tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateUnicodeData)
}

tasks.matching {
    it.name.endsWith("sourcesjar", ignoreCase = true) || it.name.contains("dokka")
}.configureEach {
    dependsOn(generateUnicodeData)
}
