import me.zolotov.kodepoint.generator.generateUnicodeData
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    id("kodepoint.multiplatform")
}

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/sources/unicode-data"))
            dependencies {
                implementation(project(":common"))
            }
        }
        jvmTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

val generateUnicodeData by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/sources/unicode-data")
    val cacheDir = layout.buildDirectory.dir("unicode-cache")
    val characterDataMetricsReport = layout.buildDirectory.file("reports/character-data/metrics.json")
    outputs.dir(outputDir)
    outputs.file(characterDataMetricsReport)

    doLast {
        generateUnicodeData(
            outputDir.get().asFile.toPath(),
            cacheDir.get().asFile.toPath(),
            "Generated by ./gradlew :unicode:generateUnicodeData",
            characterDataMetricsReport.get().asFile.toPath()
        )
    }
}

tasks.register("characterDataMetrics") {
    group = "reporting"
    description = "Generate CharacterData size metrics as JSON."
    dependsOn(generateUnicodeData)
    doLast {
        println("CharacterData metrics report: ${layout.buildDirectory.file("reports/character-data/metrics.json").get().asFile}")
    }
}

tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateUnicodeData)
}

tasks.matching {
    it.name.endsWith("sourcesjar", ignoreCase = true) || it.name.contains("dokka")
}.configureEach {
    dependsOn(generateUnicodeData)
}
