name: "Tests"

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            tasks: jvmTest jsTest wasmJsTest linuxX64Test
          - os: macos-latest
            tasks: jvmTest iosSimulatorArm64Test macosArm64Test tvosSimulatorArm64Test watchosSimulatorArm64Test
          - os: windows-latest
            tasks: jvmTest mingwX64Test

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'temurin'
          java-version: 24

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@90ddb51e90a5fd9ba75f40cf85156b7b41bf76a3 # v6

      - name: Run tests
        run: ./gradlew ${{ matrix.tasks }}

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@1cc81a5edf733718d4850df304aaa21c05cd7280 # v3
        with:
          name: Tests Report (${{ matrix.os }})
          path: "**/build/test-results/**/*.xml"
          reporter: java-junit